import { Edit2, Trash2 } from "lucide-react";
import type { Task } from "../../types";

const PRIORITY_LABEL: Record<Task["priority"], string> = {
  high: "高",
  medium: "中",
  low: "低",
};
const PRIORITY_CLASS: Record<Task["priority"], string> = {
  high: "text-red-500",
  medium: "text-yellow-600",
  low: "text-gray-400",
};

interface TaskRowProps {
  task: Task;
  productName?: string;
  editingTaskId: string | null;
  taskEditDraft: Partial<Task>;
  onToggle: (id: string, done: boolean) => void;
  onStartEdit: (t: Task) => void;
  onSaveEdit: (id: string) => void;
  onCancelEdit: () => void;
  onEditDraftChange: (patch: Partial<Task>) => void;
  onRemove: (id: string) => void;
}

export function TaskRow({
  task,
  productName,
  editingTaskId,
  taskEditDraft,
  onToggle,
  onStartEdit,
  onSaveEdit,
  onCancelEdit,
  onEditDraftChange,
  onRemove,
}: TaskRowProps) {
  const isEditing = editingTaskId === task.id;
  const isAutoGenerated = task.sourceMasterId !== undefined;

  if (isEditing) {
    return (
      <div className="bg-gray-50 rounded-lg p-3 space-y-2 mb-1">
        <input
          type="text"
          value={taskEditDraft.title ?? ""}
          onChange={(e) =>
            onEditDraftChange({ ...taskEditDraft, title: e.target.value })
          }
          className="w-full border border-gray-300 rounded-lg px-3 py-1.5 text-sm focus:ring-2 focus:ring-blue-300 outline-none"
          autoFocus
        />
        <div className="flex gap-2">
          <input
            type="date"
            value={taskEditDraft.dueDate ?? ""}
            onChange={(e) =>
              onEditDraftChange({
                ...taskEditDraft,
                dueDate: e.target.value || undefined,
              })
            }
            className="flex-1 border border-gray-300 rounded-lg px-3 py-1.5 text-sm"
          />
          <select
            value={taskEditDraft.priority ?? "medium"}
            onChange={(e) =>
              onEditDraftChange({
                ...taskEditDraft,
                priority: e.target.value as Task["priority"],
              })
            }
            className="border border-gray-300 rounded-lg px-2 py-1.5 text-sm"
          >
            <option value="high">高</option>
            <option value="medium">中</option>
            <option value="low">低</option>
          </select>
        </div>
        <input
          type="text"
          placeholder="メモ（任意）"
          value={taskEditDraft.memo ?? ""}
          onChange={(e) =>
            onEditDraftChange({
              ...taskEditDraft,
              memo: e.target.value || undefined,
            })
          }
          className="w-full border border-gray-300 rounded-lg px-3 py-1.5 text-sm"
        />
        <div className="flex justify-end gap-2">
          <button
            onClick={onCancelEdit}
            className="px-3 py-1 text-xs text-gray-600 hover:bg-gray-100 rounded-lg"
          >
            キャンセル
          </button>
          <button
            onClick={() => onSaveEdit(task.id)}
            className="px-3 py-1 text-xs bg-blue-500 text-white rounded-lg hover:bg-blue-600"
          >
            保存
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-3 py-2.5 px-1 rounded-lg hover:bg-gray-50 group">
      <input
        type="checkbox"
        checked={task.done}
        onChange={(e) => onToggle(task.id, e.target.checked)}
        className="w-4 h-4 accent-blue-500 rounded flex-shrink-0"
      />
      <span className="flex-1 min-w-0">
        <span
          className={`text-sm ${task.done ? "line-through text-gray-400" : "text-gray-800"}`}
        >
          {task.title}
        </span>
        {productName && (
          <span className="ml-1.5 text-xs text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded">
            {productName}
          </span>
        )}
        {isAutoGenerated && (
          <span className="ml-1.5 text-xs text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded">
            自動
          </span>
        )}
        {task.dueDate && (
          <span className="ml-1.5 text-xs text-gray-500">
            期限: {task.dueDate}
          </span>
        )}
        {task.done && task.doneDate && (
          <span className="ml-1.5 text-xs text-green-600">
            完了: {task.doneDate}
          </span>
        )}
        <span
          className={`ml-1.5 text-xs ${PRIORITY_CLASS[task.priority ?? "medium"]}`}
        >
          [{PRIORITY_LABEL[task.priority ?? "medium"]}]
        </span>
      </span>
      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0">
        <button
          onClick={() => onStartEdit(task)}
          className="p-1.5 text-gray-400 hover:text-blue-500 rounded"
          title="編集"
        >
          <Edit2 className="w-3.5 h-3.5" />
        </button>
        {!isAutoGenerated && (
          <button
            onClick={() => onRemove(task.id)}
            className="p-1.5 text-gray-400 hover:text-red-500 rounded"
            title="削除"
          >
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        )}
      </div>
    </div>
  );
}
