// =====================================================
// Store _internal barrel — re-exports AppState + types
// =====================================================
export type { AppState } from "./appstate";
export type {
  Toast,
  EmailChangeRequest,
  User,
  Team,
  Customer,
  DailyReport,
  Template,
  QuickChip,
  Notification,
  AuditLog,
  TimeBlock,
  Todo,
  Comment,
  Role,
  TrackingSession,
  BlockType,
  ManagerComment,
  Compliment,
  Person,
  Opportunity,
  OpportunityStage,
  Policy,
  PolicyStatusHistory,
  Coverage,
  PolicyStatus,
  CoverageType,
  ProductCategory,
  SalesTarget,
  TargetScope,
  TargetPeriodType,
  OpportunityActivityReport,
  ProposalRound,
  Task,
  TaskTemplate,
  TaskTimingType,
  TaskBaseDateType,
  Household,
  ProposalProduct,
  SalesChannel,
  AuthSession,
  RenewalCase,
  RenewalSurvey,
  RenewalStatus,
  RenewalLogKind,
  CustomerInteraction,
  InteractionKind,
  InsuranceCompany,
  ProductCategoryMaster,
} from "./exportedTypes";
